# Generated by Django 5.0 on 2024-04-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddChicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('birds', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'addchicks_table',
            },
        ),
        migrations.CreateModel(
            name='AddFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_no', models.CharField(max_length=100)),
                ('bags', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'addfeed_table',
            },
        ),
        migrations.CreateModel(
            name='AddLifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_Code', models.CharField(max_length=50)),
                ('Driver_Name', models.CharField(max_length=100)),
                ('Vehicle_No', models.CharField(max_length=20)),
                ('No_of_Boxes', models.IntegerField()),
            ],
            options={
                'db_table': 'addlifting_table',
            },
        ),
        migrations.CreateModel(
            name='AddMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('administration_method', models.CharField(choices=[('oral', 'Oral'), ('injection', 'Injection'), ('topical', 'Topical')], max_length=50)),
                ('additional_notes', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'addmedicine_table',
            },
        ),
        migrations.CreateModel(
            name='AddMortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cause_of_death', models.CharField(choices=[('disease', 'Disease'), ('accident', 'Accident'), ('other', 'Other')], max_length=50)),
                ('Number_of_Birds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addmortality_table',
            },
        ),
        migrations.CreateModel(
            name='AddVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('dose', models.CharField(max_length=50)),
                ('administration_method', models.CharField(choices=[('injection', 'Injection'), ('oral', 'Oral'), ('spray', 'Spray')], max_length=50)),
                ('notes', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'addvaccine_table',
            },
        ),
    ]
