# Generated by Django 5.0 on 2024-03-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddChicksTable',
            new_name='AddChicks',
        ),
    ]
