# Generated by Django 5.0 on 2024-04-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlifting',
            name='No_of_Boxes',
        ),
    ]
