# Generated by Django 5.0 on 2024-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlifting',
            name='box_data',
            field=models.CharField(default='0_0_0', max_length=400),
        ),
    ]
