# Generated by Django 5.0 on 2024-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_addlifting_no_of_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlifting',
            name='box_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlifting',
            name='total_birds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlifting',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
