# Generated by Django 5.0 on 2024-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_addlifting_box_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlifting',
            name='birds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlifting',
            name='box_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlifting',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
