# Generated by Django 5.0 on 2024-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_addmortality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmortality',
            name='notes',
        ),
        migrations.AddField(
            model_name='addmortality',
            name='Number_of_Birds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
