# Generated by Django 5.0 on 2024-03-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_addmortality_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmortality',
            name='batch_number',
        ),
    ]
