# Generated by Django 5.0 on 2024-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_addmortality_batch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_no', models.CharField(max_length=100)),
                ('bags', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'addfeed_table',
            },
        ),
    ]
