# Generated by Django 5.0 on 2024-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_addfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('administration_method', models.CharField(choices=[('oral', 'Oral'), ('injection', 'Injection'), ('topical', 'Topical')], max_length=50)),
                ('additional_notes', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'addmedicine_table',
            },
        ),
    ]
