# Generated by Django 5.0 on 2024-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_addmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('dose', models.CharField(max_length=50)),
                ('method', models.CharField(choices=[('injection', 'Injection'), ('oral', 'Oral'), ('spray', 'Spray')], max_length=50)),
                ('notes', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'addvaccine_table',
            },
        ),
    ]
