# Generated by Django 5.0 on 2024-03-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_addvaccine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvaccine',
            old_name='method',
            new_name='administration_method',
        ),
    ]
