# Generated by Django 5.0 on 2024-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_method_addvaccine_administration_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('customer_code', models.CharField(max_length=50)),
                ('farm_code', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('num_birds', models.IntegerField()),
                ('num_cages', models.IntegerField()),
            ],
            options={
                'db_table': 'addlifting_table',
            },
        ),
    ]
